version: "3.9"

services:
  web:
    build: .
    command:  >
      sh -c "python manage.py migrate --settings=ChickoMenu.settings.development &&
             python manage.py runserver 0.0.0.0:8089 --settings=ChickoMenu.settings.development"
    volumes:
      - .:/code
    ports:
      - 8089:8089
    depends_on:
      - db
    env_file:
      - "./.env.db"
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    build: ./
    command: celery -A ChickoMenu worker -l info 
    env_file:
      - "./.env"
    volumes:
      - .:/code
    depends_on:
      - redis

  flower:
    build: .
    command: celery  -A ChickoMenu --broker=redis://redis:6379  flower 
    volumes:
      - .:/code
    depends_on:
      - redis
      - celery
    ports:
      - "5555:5555"
volumes:
  postgres_data: