# Generated by Django 4.1.10 on 2023-07-10 08:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plan', '0005_alter_plan_modified_at_alter_planitem_modified_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('payable_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('authority', models.CharField(blank=True, max_length=36, null=True)),
                ('user_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.userplan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
