# Generated by Django 4.1 on 2023-06-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plans',
            field=models.ManyToManyField(through='plan.UserPlan', to='plan.plan'),
        ),
    ]
