# Generated by Django 4.1 on 2023-06-16 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_alter_userplan_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userplan',
            unique_together=set(),
        ),
    ]
