# Generated by Django 4.1 on 2023-06-16 14:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plan', '0003_alter_userplan_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userplan',
            unique_together={('user', 'plan', 'is_active', 'id')},
        ),
    ]
