# Generated by Django 4.1 on 2023-07-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_alter_userplan_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='planitem',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
