# Generated by Django 4.1 on 2023-05-22 22:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menu_last_time_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='last_time_paid',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
