# Generated by Django 4.1 on 2023-05-22 21:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menu_last_time_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='last_time_paid',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 22, 21, 54, 4, 567741)),
        ),
    ]
