# Generated by Django 4.1 on 2023-05-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='theme_image'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='theme_preview'),
        ),
    ]
