# Generated by Django 4.1 on 2023-06-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0002_alter_theme_background_image_alter_theme_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
