# Generated by Django 4.1 on 2023-06-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0003_alter_theme_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theme',
            old_name='background_image',
            new_name='header_image',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='description',
        ),
        migrations.AddField(
            model_name='theme',
            name='header_color',
            field=models.CharField(default='#343a40', max_length=7),
        ),
        migrations.AddField(
            model_name='theme',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='theme_image'),
        ),
    ]
