# Generated by Django 4.1 on 2023-07-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0005_alter_theme_font_family_alter_theme_header_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='menu_item_background_color',
            field=models.CharField(default='#808080', max_length=7),
        ),
        migrations.AlterField(
            model_name='theme',
            name='menu_background_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='theme',
            name='menu_text_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
